# Generated by Django 6.0.6 on 2026-06-07 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=200)),
                ('installation_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('calibrating', 'Calibrating'), ('broken_down', 'Broken Down'), ('scheduled_maintenance', 'Under Scheduled Maintenance'), ('out_of_service', 'Out of Service')], default='operational', max_length=30)),
                ('qr_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('user_manual', models.FileField(blank=True, null=True, upload_to='manuals/')),
                ('calibration_guideline', models.FileField(blank=True, null=True, upload_to='guidelines/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='instruments.vendor')),
            ],
        ),
    ]
