# Generated by Django 6.0.6 on 2026-06-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
