# Generated by Django 6.0.6 on 2026-06-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_instrument_installation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='vendor',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=15, verbose_name='IFSC / Swift Code'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, verbose_name='GSTIN / Tax ID'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan',
            field=models.CharField(blank=True, max_length=15, verbose_name='PAN'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='e.g. Net 30, 50% advance', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5 star rating', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='service_type',
            field=models.CharField(blank=True, choices=[('calibration', 'Calibration'), ('amc', 'AMC / Maintenance'), ('supply', 'Parts Supply'), ('repair', 'Repair & Service'), ('installation', 'Installation'), ('multiple', 'Multiple Services')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
