# Generated by Django 6.0.6 on 2026-06-07 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('non_comprehensive', 'Non-Comprehensive')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='amc_contracts/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending_renewal', 'Pending Renewal')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amc_contracts', to='instruments.instrument')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amc_contracts', to='instruments.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='BreakdownTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('description', models.TextField()),
                ('resolution_notes', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_tickets', to='instruments.instrument')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='calibration_certs/')),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('due_soon', 'Due Soon')], default='valid', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calibrated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_records', to='instruments.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('calibration', 'Calibration'), ('amc_visit', 'AMC Vendor Visit')], max_length=15)),
                ('description', models.TextField()),
                ('parts_used', models.TextField(blank=True)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('performed_at', models.DateTimeField()),
                ('next_maintenance_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='instruments.instrument')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to='maintenance.breakdownticket')),
            ],
        ),
    ]
