# Generated by Django 6.0.6 on 2026-06-07 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('calibration', 'Calibration Report'), ('amc', 'AMC / Contract Report'), ('vendors', 'Vendor List'), ('service_month', 'Service Month Report'), ('audit', 'Audit Readiness Report')], max_length=30, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('header_text', models.TextField(blank=True, help_text='Extra text shown below company name in header')),
                ('footer_text', models.TextField(blank=True, help_text='Custom footer text (left side)')),
                ('include_logo', models.BooleanField(default=True)),
                ('show_address', models.BooleanField(default=True)),
                ('show_page_number', models.BooleanField(default=True)),
                ('show_generated_date', models.BooleanField(default=True)),
                ('custom_columns', models.JSONField(blank=True, default=list, help_text='List of column keys to include/exclude')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='companysettings',
            name='equipment_code_digits',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='equipment_code_prefix',
            field=models.CharField(blank=True, default='EQ', max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='equipment_code_separator',
            field=models.CharField(blank=True, default='-', max_length=5),
        ),
        migrations.CreateModel(
            name='CustomOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('department', 'Department'), ('location', 'Location / Room'), ('instrument_category', 'Instrument Category'), ('maintenance_type', 'Maintenance Type'), ('spare_part_category', 'Spare Part Category')], max_length=50)),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['field', 'sort_order', 'label'],
                'unique_together': {('field', 'value')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruments_view', models.BooleanField(default=True)),
                ('instruments_edit', models.BooleanField(default=False)),
                ('calibration_view', models.BooleanField(default=True)),
                ('calibration_edit', models.BooleanField(default=False)),
                ('service_view', models.BooleanField(default=True)),
                ('service_edit', models.BooleanField(default=False)),
                ('inventory_view', models.BooleanField(default=True)),
                ('inventory_edit', models.BooleanField(default=False)),
                ('reports_view', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
