# Generated by Django 6.0.6 on 2026-06-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_pdftemplate_companysettings_equipment_code_digits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftemplate',
            name='accent_color',
            field=models.CharField(blank=True, default='#f1f5f9', max_length=7),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='body_font_size',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='confidential_text',
            field=models.CharField(blank=True, default='CONFIDENTIAL — FOR INTERNAL USE ONLY', max_length=200),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='margin_bottom',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='margin_left',
            field=models.FloatField(default=15.0),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='margin_right',
            field=models.FloatField(default=15.0),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='margin_top',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4'), ('Letter', 'US Letter'), ('A3', 'A3')], default='A4', max_length=10),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='primary_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='show_alt_row_color',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='show_confidential_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='show_signature_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='show_table_borders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='show_watermark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='signature_label',
            field=models.CharField(blank=True, default='Authorised Signatory', max_length=100),
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='watermark_text',
            field=models.CharField(blank=True, default='DRAFT', max_length=100),
        ),
        migrations.AlterField(
            model_name='pdftemplate',
            name='custom_columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='pdftemplate',
            name='footer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pdftemplate',
            name='header_text',
            field=models.TextField(blank=True),
        ),
    ]
