# Generated by Django 6.0.6 on 2026-06-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_pdf_template_expanded'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='company_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='department_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='sub_dept_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
